### ISSUE TITLE
build issue on ubuntu

### ISSUE THREAD

**Issue by JasonGaos** [osu-crypto/libOTe#100] opened 2022-12-13 18:46 UTC
Hello Professor,

I met some building issue like this with command "python3 build.py --all --boost --sodium --relic"

could you please help?
Thanks
![1](https://user-images.githubusercontent.com/31381946/207418814-891c5760-2e73-4c1c-a346-5d7efe0e3967.jpg)

**Comment by ladnir** [comment] 2022-12-14 16:25
Please give more output. You didn't include the actual error

**Comment by JasonGaos** [comment] 2022-12-14 16:53
My bad. Here it is.
![1](https://user-images.githubusercontent.com/31381946/207658098-eacf9516-220a-4ced-b4a6-c2edd803035b.jpg)

**Comment by ladnir** [comment] 2022-12-14 18:30
Is it true that you first built & installed libOTe and now you are trying to enable boost?

If so, try building as `python3 build.py -DFETCH_COPROTO=true`

**Comment by JasonGaos** [comment] 2022-12-14 19:04
It gives the same error message.
I build it with "python3 build.py --all --boost --sodium --relic". want to enable boost now indeed. not sure why "--boost" does not enable it at first place.

**Comment by ladnir** [comment] 2022-12-14 19:11
ideally, it should but evidently, my cmake code has a bug. :(

To be clear, you first built without boost and now building with boost. Is that correct?

So I will investigate & work on a long-term fix but that will take a bit of time. As a short-term workaround, you can uninstall and then build with your full set of options.

To uninstall you will need to delete, 

- `/usr/local/lib/cmake/libOTe`
- `/usr/local/lib/cmake/cryptoTools`
- `/usr/local/lib/cmake/coproto`

You can then build with `python3 build.py --all --boost --sodium --relic`

Note that you don't need both sodium and relic. If unsure just use sodium.

**Comment by JasonGaos** [comment] 2022-12-14 20:22
Thank you. 

Actually, I tried to build and install it sometimes before but never uninstall anything. So I think this may cause the situation like you said: build without boost and now building with it.

I will uninstall everything and try what you suggest.

I need to use the elliptic curve part in the cryptotools library so I think relic is what I need. Am I right about this?

**Comment by ladnir** [comment] 2022-12-14 20:32
sodium and relic both do this. There are differences between them but if you just want a base OT, then either works.

**Comment by ladnir** [comment] 2022-12-15 17:26
So, i think this issue might actually be fixed in the current version. I suspect the problem is that you had an old version installed and the old version didn't support changing boost after install. Not it should be supported. So im going to close this assuming you got it working

**Comment by JasonGaos** [comment] 2022-12-16 03:29
Thank you so much for your help.

**Closed** 2023-01-17 06:08 UTC
